//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aplikacja
{
    using System;
    using System.Collections.Generic;
    
    public partial class Klient
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Klient()
        {
            this.Umowa_sprzedaz_hurt = new HashSet<Umowa_sprzedaz_hurt>();
            this.Zamowienie = new HashSet<Zamowienie>();
        }
    
        public int ID_klient { get; set; }
        public string Nazwisko { get; set; }
        public string Imie { get; set; }
        public string Nazwa_firmy { get; set; }
        public string NIP { get; set; }
        public string Nr_telefonu_1 { get; set; }
        public string Nr_telefonu_2 { get; set; }
        public string Email { get; set; }
        public string Miasto { get; set; }
        public string Kod_pocztowy { get; set; }
        public string Ulica { get; set; }
        public Nullable<int> Nr_domu { get; set; }
        public Nullable<int> Nr_lokalu { get; set; }
        public int ID_status_klient { get; set; }
    
        public virtual Status_klient Status_klient { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Umowa_sprzedaz_hurt> Umowa_sprzedaz_hurt { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zamowienie> Zamowienie { get; set; }
    }
}
