//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aplikacja
{
    using System;
    using System.Collections.Generic;
    
    public partial class Magazyn
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Magazyn()
        {
            this.Miejsce_magazynowania = new HashSet<Miejsce_magazynowania>();
        }
    
        public int ID_magazyn { get; set; }
        public string Nazwa { get; set; }
        public Nullable<int> Pojemnosc_w_m3 { get; set; }
        public Nullable<int> ID_dzial { get; set; }
        public Nullable<int> ID_typ_magazynowania { get; set; }
    
        public virtual Dzial Dzial { get; set; }
        public virtual Typ_magazynowania Typ_magazynowania { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Miejsce_magazynowania> Miejsce_magazynowania { get; set; }
    }
}
