//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aplikacja
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parametr_rodzaj_transport
    {
        public int ID_parametr_pojazd_transport { get; set; }
        public int ID_pojazd_transport { get; set; }
        public int ID_typ_parametr_pojazd_transport { get; set; }
        public int Wartosc { get; set; }
    
        public virtual Pojazd_transport Pojazd_transport { get; set; }
        public virtual Typ_parametr_pojazd_transport Typ_parametr_pojazd_transport { get; set; }
    }
}
