//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aplikacja
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pojazd_transport
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pojazd_transport()
        {
            this.Parametr_rodzaj_transport = new HashSet<Parametr_rodzaj_transport>();
            this.Rozladunek = new HashSet<Rozladunek>();
            this.Wysylka_detal = new HashSet<Wysylka_detal>();
            this.Wysylka_hurt = new HashSet<Wysylka_hurt>();
        }
    
        public int ID_pojazd_transport { get; set; }
        public string Marka { get; set; }
        public string Model { get; set; }
        public string Nr_rejestracyjny { get; set; }
        public int ID_typ_pojad_transport { get; set; }
        public int ID_rodzaj_pojazd_transport { get; set; }
        public int ID_stan_techniczny_pojazd_transport { get; set; }
        public decimal Sr_spalanie_wg_producenta { get; set; }
        public int ID_typ_paliwa { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Parametr_rodzaj_transport> Parametr_rodzaj_transport { get; set; }
        public virtual Rodzaj_pojazd_transport Rodzaj_pojazd_transport { get; set; }
        public virtual Stan_techniczny_pojazd_transport Stan_techniczny_pojazd_transport { get; set; }
        public virtual Typ_pojazd_transport Typ_pojazd_transport { get; set; }
        public virtual Typ_paliwa Typ_paliwa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rozladunek> Rozladunek { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Wysylka_detal> Wysylka_detal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Wysylka_hurt> Wysylka_hurt { get; set; }
    }
}
