//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aplikacja
{
    using System;
    using System.Collections.Generic;
    
    public partial class Poziom_magazynowanie
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Poziom_magazynowanie()
        {
            this.Miejsce_magazynowania = new HashSet<Miejsce_magazynowania>();
            this.Parametr_poziom_magazynowanie = new HashSet<Parametr_poziom_magazynowanie>();
        }
    
        public int ID_poziom_magazynowanie { get; set; }
        public string Poziom { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Miejsce_magazynowania> Miejsce_magazynowania { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Parametr_poziom_magazynowanie> Parametr_poziom_magazynowanie { get; set; }
    }
}
