//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aplikacja
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produkt
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Produkt()
        {
            this.Atrybut = new HashSet<Atrybut>();
            this.Dostawa_szczegol = new HashSet<Dostawa_szczegol>();
            this.Miejsce_magazynowania = new HashSet<Miejsce_magazynowania>();
            this.Oferta_handlowa_szczegol = new HashSet<Oferta_handlowa_szczegol>();
            this.Sprzedaz_szczegol_hurt = new HashSet<Sprzedaz_szczegol_hurt>();
            this.Sprzedaz_szczegol_detal = new HashSet<Sprzedaz_szczegol_detal>();
            this.Szczegol_reklamacja_hurt = new HashSet<Szczegol_reklamacja_hurt>();
            this.Szczegol_reklamacja_detal = new HashSet<Szczegol_reklamacja_detal>();
            this.Utylizacja = new HashSet<Utylizacja>();
            this.Zamowienie_szczegol = new HashSet<Zamowienie_szczegol>();
        }
    
        public int ID_produkt { get; set; }
        public string Nazwa { get; set; }
        public int ID_producent { get; set; }
        public int ID_typ_produkt { get; set; }
        public int Nr_produkt { get; set; }
        public decimal Cena_sugerowana_netto { get; set; }
        public Nullable<int> Termin_magazynowania_miesiace { get; set; }
        public Nullable<int> Termin_przydatnosci_miesiace { get; set; }
        public decimal Objetosc_magazynowa_m3 { get; set; }
        public int ID_gwarancja { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Atrybut> Atrybut { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Dostawa_szczegol> Dostawa_szczegol { get; set; }
        public virtual Gwarancja Gwarancja { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Miejsce_magazynowania> Miejsce_magazynowania { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Oferta_handlowa_szczegol> Oferta_handlowa_szczegol { get; set; }
        public virtual Producent Producent { get; set; }
        public virtual Typ_produkt Typ_produkt { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sprzedaz_szczegol_hurt> Sprzedaz_szczegol_hurt { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sprzedaz_szczegol_detal> Sprzedaz_szczegol_detal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Szczegol_reklamacja_hurt> Szczegol_reklamacja_hurt { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Szczegol_reklamacja_detal> Szczegol_reklamacja_detal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Utylizacja> Utylizacja { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zamowienie_szczegol> Zamowienie_szczegol { get; set; }
    }
}
