//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aplikacja
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rozladunek
    {
        public int ID_rozladunek { get; set; }
        public int ID_dostawa { get; set; }
        public int ID_pojazd_transport { get; set; }
        public int ID_pracownik { get; set; }
        public System.DateTime Data_rozladunek { get; set; }
    
        public virtual Dostawa Dostawa { get; set; }
        public virtual Pojazd_transport Pojazd_transport { get; set; }
        public virtual Pracownik Pracownik { get; set; }
    }
}
