//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aplikacja
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_All_clients
    {
        public string Nazwisko { get; set; }
        public string Imię { get; set; }
        public string Numer_telefonu { get; set; }
        public string Status_klienta { get; set; }
        public string Adres_e_mail { get; set; }
        public string Firma { get; set; }
        public int ID { get; set; }
    }
}
