//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aplikacja
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_All_hurt_sold_products_magazyn_part2
    {
        public int ID { get; set; }
        public string Nazwa_produktu { get; set; }
        public int Numer_produktu { get; set; }
        public Nullable<int> Ilosc { get; set; }
    }
}
