//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aplikacja
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_Edit_client
    {
        public int ID { get; set; }
        public string Nazwisko { get; set; }
        public string Imię { get; set; }
        public string Nazwa_firmy { get; set; }
        public string NIP { get; set; }
        public string Nr_telefon_1 { get; set; }
        public string Nr_telefon_2 { get; set; }
        public string Email { get; set; }
        public string Miasto { get; set; }
        public string Kod_pocztowy { get; set; }
        public string Ulica { get; set; }
        public Nullable<int> Nr_domu { get; set; }
        public Nullable<int> Nr_lokali { get; set; }
        public string Status_klienta { get; set; }
    }
}
