//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aplikacja
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_Last_180_Sales_detal
    {
        public int ID_produktu { get; set; }
        public string Produkt { get; set; }
        public int Nr_produktu { get; set; }
        public Nullable<int> Planowany_popyt_miesięczny { get; set; }
        public System.DateTime Data_sprzedazy { get; set; }
    }
}
