//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aplikacja
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_New_detal_sales
    {
        public System.DateTime Data_sprzedazy { get; set; }
        public string Forma_platnosci { get; set; }
        public System.DateTime Termin_zaplaty { get; set; }
        public string Forma_odbioru { get; set; }
        public int ID { get; set; }
    }
}
