//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aplikacja
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_New_detal_sales_details
    {
        public int ID { get; set; }
        public string Produkt { get; set; }
        public decimal Cena_sugerowana_netto { get; set; }
        public string Jednostka { get; set; }
        public int Podatek_VAT { get; set; }
        public int Ilosc { get; set; }
        public int Nr_sprzedazy { get; set; }
    }
}
