//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aplikacja
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_Oferta_handlowa_zaakceptowane
    {
        public int Numer_oferty { get; set; }
        public string Imię { get; set; }
        public string Nazwisko { get; set; }
        public System.DateTime Termin_realizaji { get; set; }
        public string Status_oferty { get; set; }
    }
}
