//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aplikacja
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_Oferta_handlowa_szczegol
    {
        public Nullable<int> Numer_oferty { get; set; }
        public string Produkt { get; set; }
        public Nullable<int> Ilosc { get; set; }
        public Nullable<decimal> Cena_netto_za_jednostkę { get; set; }
        public int Podatek_VAT__ { get; set; }
    }
}
