//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aplikacja
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_Procent_magazyn
    {
        public string Numer_magazynu { get; set; }
        public string Dział_magazynu { get; set; }
        public Nullable<decimal> Procent { get; set; }
    }
}
