//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aplikacja
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_Pracownik_add
    {
        public int ID_pracownik { get; set; }
        public string Imię { get; set; }
        public string Nazwisko { get; set; }
        public string Wykształcenie { get; set; }
        public string Numer_telefonu { get; set; }
        public string E_mail { get; set; }
        public string Miasto { get; set; }
        public string Kod_pocztowy { get; set; }
        public string Ulica { get; set; }
        public int Numer_budynku { get; set; }
        public Nullable<int> Numer_lokalu { get; set; }
        public string Numer_dowodu { get; set; }
        public string PESEL { get; set; }
    }
}
