//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aplikacja
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_Reklamacja_detal_szczegol
    {
        public int Numer_reklamacji { get; set; }
        public int No_produktu { get; set; }
        public string Rodzaj_reklamacji { get; set; }
        public string Produkt { get; set; }
        public int ID { get; set; }
        public int Ilość { get; set; }
        public bool Utylizacja { get; set; }
        public string Uwagi { get; set; }
    }
}
