//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aplikacja
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_Reklamacja_detal
    {
        public int Numer_reklamacji { get; set; }
        public System.DateTime Data_reklamacji { get; set; }
        public int Numer_sprzedaży { get; set; }
        public string Imię_pracownika { get; set; }
        public string Nazwisko_pracownika { get; set; }
        public string Opis { get; set; }
    }
}
