//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aplikacja
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_Sprzedaz_hurt_klient_detalis
    {
        public int ID { get; set; }
        public string Produkt { get; set; }
        public int Numer_produktu { get; set; }
        public int Ilośc { get; set; }
        public int Nr_sprzedazy { get; set; }
        public decimal Cena_za_szt_ { get; set; }
        public Nullable<decimal> Cena_sprzedazy { get; set; }
    }
}
