//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aplikacja
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_Sprzedaz_hurt_klient
    {
        public System.DateTime Data_sprzedazy { get; set; }
        public string Nazwisko_klienta { get; set; }
        public string Imię_klienta { get; set; }
        public string Status_klienta { get; set; }
        public int ID { get; set; }
    }
}
