//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aplikacja
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_Sprzedaz_hurt
    {
        public int Numer_sprzedaży { get; set; }
        public int Numer_zamowienia { get; set; }
        public System.DateTime Data_sprzedaży { get; set; }
        public string Forma_odbioru { get; set; }
        public string Forma_płatności { get; set; }
        public System.DateTime Termin_płatności { get; set; }
    }
}
