//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aplikacja
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_Sprzedaz_szczegol_hurt
    {
        public int Numer_sprzedaży { get; set; }
        public int Numer_szczegółu { get; set; }
        public string Nazwa_produktu { get; set; }
        public string Jednostka { get; set; }
        public int Ilość { get; set; }
        public decimal Sugerowana_cena_netto { get; set; }
    }
}
