//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aplikacja
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_Umowa_sprzedazy_hurt
    {
        public int Numer_umowy_sprzedazy { get; set; }
        public int Numer_oferty_handlowej { get; set; }
        public string Imię_klienta { get; set; }
        public string Nazwisko_klienta { get; set; }
        public string Imię_pracownika { get; set; }
        public string Nazwisko_pracownika { get; set; }
    }
}
