//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aplikacja
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_Zajetosc_magazynow
    {
        public long ID { get; set; }
        public string Numer_magazynu { get; set; }
        public string Nazwa_działu { get; set; }
        public Nullable<decimal> Procent_zajetosci { get; set; }
    }
}
