//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aplikacja
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_Zamowienie
    {
        public int Numer_zamowienia { get; set; }
        public int Numer_umowy { get; set; }
        public string Imie_pracownika { get; set; }
        public string Nazwisko_pracownika { get; set; }
        public string Imię_klienta { get; set; }
        public string Naziwsko_klienta { get; set; }
        public string Stan_realizacji { get; set; }
        public System.DateTime Dara_zamówienia { get; set; }
        public int Numer_oferty { get; set; }
    }
}
