//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aplikacja
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_Zwroty_hurt
    {
        public int ID_produkt { get; set; }
        public string Produkt { get; set; }
        public int Nr_produktu { get; set; }
        public Nullable<int> Ilosc { get; set; }
    }
}
