//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aplikacja
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wysylka_hurt
    {
        public int ID_wysylka_hurt { get; set; }
        public int ID_sprzedaz_usluga_hurt { get; set; }
        public int ID_pojazd_transport { get; set; }
        public int ID_pracownik { get; set; }
        public System.DateTime Data_wysylka { get; set; }
    
        public virtual Pojazd_transport Pojazd_transport { get; set; }
        public virtual Pracownik Pracownik { get; set; }
        public virtual Sprzedaz_usluga_hurt Sprzedaz_usluga_hurt { get; set; }
    }
}
