//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aplikacja
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zamowienie
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Zamowienie()
        {
            this.Sprzedaz_hurt = new HashSet<Sprzedaz_hurt>();
            this.Zamowienie_szczegol = new HashSet<Zamowienie_szczegol>();
        }
    
        public int ID_zamowienie { get; set; }
        public int ID_umowa_sprzedaz_hurt { get; set; }
        public int ID_klient { get; set; }
        public int ID_pracownik { get; set; }
        public Nullable<int> ID_stan_realizaji { get; set; }
        public Nullable<int> ID_oferta_handlowa { get; set; }
        public System.DateTime Data_zamowienie { get; set; }
    
        public virtual Klient Klient { get; set; }
        public virtual Oferta_handlowa Oferta_handlowa { get; set; }
        public virtual Pracownik Pracownik { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sprzedaz_hurt> Sprzedaz_hurt { get; set; }
        public virtual Stan_realizacji Stan_realizacji { get; set; }
        public virtual Umowa_sprzedaz_hurt Umowa_sprzedaz_hurt { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zamowienie_szczegol> Zamowienie_szczegol { get; set; }
    }
}
