//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dostawa_szczegol
    {
        public int ID_dostawa_szczegol { get; set; }
        public int ID_dostawa { get; set; }
        public int ID_produkt { get; set; }
        public int Ilosc { get; set; }
        public decimal Cena_szt { get; set; }
    
        public virtual Dostawa Dostawa { get; set; }
        public virtual Produkt Produkt { get; set; }
    }
}
