//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Jednostka
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Jednostka()
        {
            this.Parametr_typ_magazynowania = new HashSet<Parametr_typ_magazynowania>();
            this.Parametr_poziom_magazynowanie = new HashSet<Parametr_poziom_magazynowanie>();
            this.Slownik_atrybut = new HashSet<Slownik_atrybut>();
            this.Sprzedaz_szczegol_hurt = new HashSet<Sprzedaz_szczegol_hurt>();
            this.Sprzedaz_szczegol_detal = new HashSet<Sprzedaz_szczegol_detal>();
            this.Typ_parametr_pojazd_transport = new HashSet<Typ_parametr_pojazd_transport>();
        }
    
        public int ID_jednostka { get; set; }
        public string Nazwa { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Parametr_typ_magazynowania> Parametr_typ_magazynowania { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Parametr_poziom_magazynowanie> Parametr_poziom_magazynowanie { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Slownik_atrybut> Slownik_atrybut { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sprzedaz_szczegol_hurt> Sprzedaz_szczegol_hurt { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sprzedaz_szczegol_detal> Sprzedaz_szczegol_detal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Typ_parametr_pojazd_transport> Typ_parametr_pojazd_transport { get; set; }
    }
}
