//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MGREntities : DbContext
    {
        public MGREntities()
            : base("name=MGREntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Alert> Alert { get; set; }
        public virtual DbSet<Atrybut> Atrybut { get; set; }
        public virtual DbSet<Czas_pracy> Czas_pracy { get; set; }
        public virtual DbSet<Dane_adresowe_pracownik> Dane_adresowe_pracownik { get; set; }
        public virtual DbSet<Dostawa> Dostawa { get; set; }
        public virtual DbSet<Dostawa_szczegol> Dostawa_szczegol { get; set; }
        public virtual DbSet<Dostawca> Dostawca { get; set; }
        public virtual DbSet<Dzial> Dzial { get; set; }
        public virtual DbSet<Dzial_pracownik> Dzial_pracownik { get; set; }
        public virtual DbSet<Email_pracownik> Email_pracownik { get; set; }
        public virtual DbSet<Etat> Etat { get; set; }
        public virtual DbSet<Forma_platnosc> Forma_platnosc { get; set; }
        public virtual DbSet<Gwarancja> Gwarancja { get; set; }
        public virtual DbSet<Jednostka> Jednostka { get; set; }
        public virtual DbSet<Kategoria> Kategoria { get; set; }
        public virtual DbSet<Klient> Klient { get; set; }
        public virtual DbSet<Miejsce_magazynowania> Miejsce_magazynowania { get; set; }
        public virtual DbSet<Nadgodziny> Nadgodziny { get; set; }
        public virtual DbSet<Nieobecnosc> Nieobecnosc { get; set; }
        public virtual DbSet<Nr_telefon_pracownik> Nr_telefon_pracownik { get; set; }
        public virtual DbSet<Oferta_handlowa> Oferta_handlowa { get; set; }
        public virtual DbSet<Oferta_handlowa_szczegol> Oferta_handlowa_szczegol { get; set; }
        public virtual DbSet<Parametr_poziom_magazynowanie> Parametr_poziom_magazynowanie { get; set; }
        public virtual DbSet<Parametr_rodzaj_transport> Parametr_rodzaj_transport { get; set; }
        public virtual DbSet<Parametr_typ_magazynowania> Parametr_typ_magazynowania { get; set; }
        public virtual DbSet<Podatek> Podatek { get; set; }
        public virtual DbSet<Podkategoria> Podkategoria { get; set; }
        public virtual DbSet<Pojazd_transport> Pojazd_transport { get; set; }
        public virtual DbSet<Posada_pracownika> Posada_pracownika { get; set; }
        public virtual DbSet<Poziom_magazynowanie> Poziom_magazynowanie { get; set; }
        public virtual DbSet<Pracownik> Pracownik { get; set; }
        public virtual DbSet<Producent> Producent { get; set; }
        public virtual DbSet<Produkt> Produkt { get; set; }
        public virtual DbSet<Rabat> Rabat { get; set; }
        public virtual DbSet<Reklamacja_detal> Reklamacja_detal { get; set; }
        public virtual DbSet<Reklamacja_hurt> Reklamacja_hurt { get; set; }
        public virtual DbSet<Rodzaj_nadgodziny> Rodzaj_nadgodziny { get; set; }
        public virtual DbSet<Rodzaj_nieobecnosci> Rodzaj_nieobecnosci { get; set; }
        public virtual DbSet<Rodzaj_pojazd_transport> Rodzaj_pojazd_transport { get; set; }
        public virtual DbSet<Rodzaj_umowy> Rodzaj_umowy { get; set; }
        public virtual DbSet<Rozladunek> Rozladunek { get; set; }
        public virtual DbSet<Slownik_atrybut> Slownik_atrybut { get; set; }
        public virtual DbSet<Sprzedaz_detal> Sprzedaz_detal { get; set; }
        public virtual DbSet<Sprzedaz_hurt> Sprzedaz_hurt { get; set; }
        public virtual DbSet<Sprzedaz_szczegol_detal> Sprzedaz_szczegol_detal { get; set; }
        public virtual DbSet<Sprzedaz_szczegol_hurt> Sprzedaz_szczegol_hurt { get; set; }
        public virtual DbSet<Sprzedaz_usluga_detal> Sprzedaz_usluga_detal { get; set; }
        public virtual DbSet<Sprzedaz_usluga_hurt> Sprzedaz_usluga_hurt { get; set; }
        public virtual DbSet<Stan_realizacji> Stan_realizacji { get; set; }
        public virtual DbSet<Stan_realizacji_dostawa> Stan_realizacji_dostawa { get; set; }
        public virtual DbSet<Stan_techniczny_pojazd_transport> Stan_techniczny_pojazd_transport { get; set; }
        public virtual DbSet<Stanowisko> Stanowisko { get; set; }
        public virtual DbSet<Status_dostawa> Status_dostawa { get; set; }
        public virtual DbSet<Status_klient> Status_klient { get; set; }
        public virtual DbSet<Status_oferta> Status_oferta { get; set; }
        public virtual DbSet<Szczegol_reklamacja_detal> Szczegol_reklamacja_detal { get; set; }
        public virtual DbSet<Szczegol_reklamacja_hurt> Szczegol_reklamacja_hurt { get; set; }
        public virtual DbSet<Szczegol_sprzedaz_usluga_detal> Szczegol_sprzedaz_usluga_detal { get; set; }
        public virtual DbSet<Szczegol_sprzedaz_usluga_hurt> Szczegol_sprzedaz_usluga_hurt { get; set; }
        public virtual DbSet<Szkolenie_pracownik> Szkolenie_pracownik { get; set; }
        public virtual DbSet<Typ_magazynowania> Typ_magazynowania { get; set; }
        public virtual DbSet<Typ_odbioru> Typ_odbioru { get; set; }
        public virtual DbSet<Typ_paliwa> Typ_paliwa { get; set; }
        public virtual DbSet<Typ_parametr_pojazd_transport> Typ_parametr_pojazd_transport { get; set; }
        public virtual DbSet<Typ_pojazd_transport> Typ_pojazd_transport { get; set; }
        public virtual DbSet<Typ_produkt> Typ_produkt { get; set; }
        public virtual DbSet<Typ_reklamacja> Typ_reklamacja { get; set; }
        public virtual DbSet<Typ_szkolenie> Typ_szkolenie { get; set; }
        public virtual DbSet<Typ_utylizacja> Typ_utylizacja { get; set; }
        public virtual DbSet<Umowa> Umowa { get; set; }
        public virtual DbSet<Umowa_sprzedaz_hurt> Umowa_sprzedaz_hurt { get; set; }
        public virtual DbSet<Usluga> Usluga { get; set; }
        public virtual DbSet<Utylizacja> Utylizacja { get; set; }
        public virtual DbSet<Wyksztalcenie> Wyksztalcenie { get; set; }
        public virtual DbSet<Wymiar_pracy> Wymiar_pracy { get; set; }
        public virtual DbSet<Wyplata> Wyplata { get; set; }
        public virtual DbSet<Wysylka_detal> Wysylka_detal { get; set; }
        public virtual DbSet<Wysylka_hurt> Wysylka_hurt { get; set; }
        public virtual DbSet<Zamowienie> Zamowienie { get; set; }
        public virtual DbSet<Zamowienie_szczegol> Zamowienie_szczegol { get; set; }
        public virtual DbSet<v_Dzial_budowa> v_Dzial_budowa { get; set; }
        public virtual DbSet<v_Dzial_kuchnia> v_Dzial_kuchnia { get; set; }
        public virtual DbSet<v_Dzial_lazienka> v_Dzial_lazienka { get; set; }
        public virtual DbSet<v_Dzial_mieszkanie> v_Dzial_mieszkanie { get; set; }
        public virtual DbSet<v_Dzial_ogrod_wypoczynek> v_Dzial_ogrod_wypoczynek { get; set; }
        public virtual DbSet<v_Dzial_technika> v_Dzial_technika { get; set; }
        public virtual DbSet<v_Products> v_Products { get; set; }
    }
}
