//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Oferta_handlowa_szczegol
    {
        public int ID_oferta_handlowa_szczegol { get; set; }
        public int ID_oferta_handlowa { get; set; }
        public int ID_produkt { get; set; }
        public int Ilosc { get; set; }
        public int Cena_netto_za_jednostke { get; set; }
        public int ID_podatek { get; set; }
    
        public virtual Oferta_handlowa Oferta_handlowa { get; set; }
        public virtual Podatek Podatek { get; set; }
        public virtual Produkt Produkt { get; set; }
    }
}
