//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parametr_typ_magazynowania
    {
        public int ID_parametr_typ_magazynowania { get; set; }
        public int ID_typ_magazynowania { get; set; }
        public string Parametr { get; set; }
        public int Wartosc_dolna { get; set; }
        public int Wartosc_gorna { get; set; }
        public int ID_jednostka { get; set; }
    
        public virtual Jednostka Jednostka { get; set; }
        public virtual Typ_magazynowania Typ_magazynowania { get; set; }
    }
}
