//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Podatek
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Podatek()
        {
            this.Oferta_handlowa_szczegol = new HashSet<Oferta_handlowa_szczegol>();
            this.Sprzedaz_szczegol_detal = new HashSet<Sprzedaz_szczegol_detal>();
        }
    
        public int ID_podatek { get; set; }
        public int Procent { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Oferta_handlowa_szczegol> Oferta_handlowa_szczegol { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sprzedaz_szczegol_detal> Sprzedaz_szczegol_detal { get; set; }
    }
}
