//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pracownik
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pracownik()
        {
            this.Czas_pracy = new HashSet<Czas_pracy>();
            this.Dane_adresowe_pracownik = new HashSet<Dane_adresowe_pracownik>();
            this.Dostawa = new HashSet<Dostawa>();
            this.Email_pracownik = new HashSet<Email_pracownik>();
            this.Nadgodziny = new HashSet<Nadgodziny>();
            this.Nieobecnosc = new HashSet<Nieobecnosc>();
            this.Nr_telefon_pracownik = new HashSet<Nr_telefon_pracownik>();
            this.Oferta_handlowa = new HashSet<Oferta_handlowa>();
            this.Reklamacja_hurt = new HashSet<Reklamacja_hurt>();
            this.Reklamacja_detal = new HashSet<Reklamacja_detal>();
            this.Rozladunek = new HashSet<Rozladunek>();
            this.Sprzedaz_usluga_hurt = new HashSet<Sprzedaz_usluga_hurt>();
            this.Sprzedaz_usluga_detal = new HashSet<Sprzedaz_usluga_detal>();
            this.Stan_realizacji_dostawa = new HashSet<Stan_realizacji_dostawa>();
            this.Szkolenie_pracownik = new HashSet<Szkolenie_pracownik>();
            this.Umowa = new HashSet<Umowa>();
            this.Wyplata = new HashSet<Wyplata>();
            this.Wysylka_detal = new HashSet<Wysylka_detal>();
            this.Wysylka_hurt = new HashSet<Wysylka_hurt>();
            this.Zamowienie = new HashSet<Zamowienie>();
        }
    
        public int ID_pracownik { get; set; }
        public string Nazwisko { get; set; }
        public string Imie { get; set; }
        public string Nr_dowodu { get; set; }
        public string PESEL { get; set; }
        public int ID_wyksztalcenie { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Czas_pracy> Czas_pracy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Dane_adresowe_pracownik> Dane_adresowe_pracownik { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Dostawa> Dostawa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Email_pracownik> Email_pracownik { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Nadgodziny> Nadgodziny { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Nieobecnosc> Nieobecnosc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Nr_telefon_pracownik> Nr_telefon_pracownik { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Oferta_handlowa> Oferta_handlowa { get; set; }
        public virtual Wyksztalcenie Wyksztalcenie { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reklamacja_hurt> Reklamacja_hurt { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reklamacja_detal> Reklamacja_detal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rozladunek> Rozladunek { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sprzedaz_usluga_hurt> Sprzedaz_usluga_hurt { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sprzedaz_usluga_detal> Sprzedaz_usluga_detal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Stan_realizacji_dostawa> Stan_realizacji_dostawa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Szkolenie_pracownik> Szkolenie_pracownik { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Umowa> Umowa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Wyplata> Wyplata { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Wysylka_detal> Wysylka_detal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Wysylka_hurt> Wysylka_hurt { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zamowienie> Zamowienie { get; set; }
    }
}
