//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sprzedaz_usluga_hurt
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sprzedaz_usluga_hurt()
        {
            this.Szczegol_sprzedaz_usluga_hurt = new HashSet<Szczegol_sprzedaz_usluga_hurt>();
            this.Wysylka_hurt = new HashSet<Wysylka_hurt>();
        }
    
        public int ID_sprzedaz_usluga_hurt { get; set; }
        public int ID_sprzedaz_hurt { get; set; }
        public int ID_pracownik { get; set; }
        public System.DateTime Termin_zaplata { get; set; }
        public int ID_forma_platnosc { get; set; }
    
        public virtual Forma_platnosc Forma_platnosc { get; set; }
        public virtual Pracownik Pracownik { get; set; }
        public virtual Sprzedaz_hurt Sprzedaz_hurt { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Szczegol_sprzedaz_usluga_hurt> Szczegol_sprzedaz_usluga_hurt { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Wysylka_hurt> Wysylka_hurt { get; set; }
    }
}
