//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sprzedaz_szczegol_detal
    {
        public int ID_sprzedaz_szczegol_detal { get; set; }
        public int ID_sprzedaz_detal { get; set; }
        public int ID_produkt { get; set; }
        public int ID_jednostka { get; set; }
        public int Cena_netto_za_jednostke { get; set; }
        public int ID_podatek { get; set; }
        public int Ilosc { get; set; }
    
        public virtual Jednostka Jednostka { get; set; }
        public virtual Podatek Podatek { get; set; }
        public virtual Produkt Produkt { get; set; }
        public virtual Sprzedaz_detal Sprzedaz_detal { get; set; }
    }
}
