//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Utylizacja
    {
        public int ID_utylizacja_magazyn { get; set; }
        public int ID_produkt { get; set; }
        public Nullable<int> ID_typ_utylizacja { get; set; }
        public int Ilosc { get; set; }
    
        public virtual Produkt Produkt { get; set; }
        public virtual Typ_utylizacja Typ_utylizacja { get; set; }
    }
}
